name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      
      - name: Build with Gradle
        run: gradle build  # Direct gradle command
      
      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: mod-jar
          path: build/libs/*.jar
